// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb2Nuki5D00zHTQXc40jGVNgz_4KZzrTE',
    appId: '1:823589653983:web:84d3a7856a39efb355886a',
    messagingSenderId: '823589653983',
    projectId: 'pedicare-1251f',
    authDomain: 'pedicare-1251f.firebaseapp.com',
    storageBucket: 'pedicare-1251f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqbLGB4b6YsMA5UT75Vxy2NY0bh5x51g0',
    appId: '1:823589653983:android:76f16322e1dec13f55886a',
    messagingSenderId: '823589653983',
    projectId: 'pedicare-1251f',
    storageBucket: 'pedicare-1251f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-95BWTUbIKc-b8aNz1qcv-5BhyQhHAfg',
    appId: '1:823589653983:ios:ca4724d139dce26755886a',
    messagingSenderId: '823589653983',
    projectId: 'pedicare-1251f',
    storageBucket: 'pedicare-1251f.firebasestorage.app',
    iosBundleId: 'com.example.projetMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-95BWTUbIKc-b8aNz1qcv-5BhyQhHAfg',
    appId: '1:823589653983:ios:ca4724d139dce26755886a',
    messagingSenderId: '823589653983',
    projectId: 'pedicare-1251f',
    storageBucket: 'pedicare-1251f.firebasestorage.app',
    iosBundleId: 'com.example.projetMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb2Nuki5D00zHTQXc40jGVNgz_4KZzrTE',
    appId: '1:823589653983:web:0c93c1441dd1c70b55886a',
    messagingSenderId: '823589653983',
    projectId: 'pedicare-1251f',
    authDomain: 'pedicare-1251f.firebaseapp.com',
    storageBucket: 'pedicare-1251f.firebasestorage.app',
  );
}
